version: '3.5'
services:
  mongo:
    image: mongo:4.2
    volumes:
      - ./mongo-data:/data/db
    ports:
      - '27017:27017'
  api:
    build:
      dockerfile: Dockerfile
      context: .
    depends_on:
      - mongo
    command: >
      uvicorn main:app --reload
    volumes:
      - ./src/:/app
    ports:
      - '11244:8000'
